Test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -43,4 +43,4 @@ jobs:
           go-version-file: "./go.mod"
 
       - name: "build"
-        run: echo "::error file=.routes/main.go,line=10,col=5::Something went wrong" 
+        run: echo "::error file=.routes/main.go,line=10,col=5::Something went wrong" && exit 1
