Test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -44,4 +44,4 @@ jobs:
           go-version-file: "./go.mod"
 
       - name: "build"
-        run: "echo \"::error file=main.go,line=10,col=15::Something went wrong\" && exit 1"
+        run: "echo \"::error file=.routes/main.go,line=10,col=5::Something went wrong\" && exit 1"
